apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-zl6a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-zl6a
    app.kubernetes.io/part-of: my-app-100
  name: devfile-sample-java-springboot-basic-zl6a
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-zl6a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-zl6a
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lpardo-tenant/my-app-100/devfile-sample-java-springboot-basic-zl6a@sha256:c2276b80472e2b9af8486d09ee7da27e67839e630ca053ebe7255b2178ce5336
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
